export default {
    en: {
        address: 'Address',
        addresses: 'Addresses',
        cancel: 'Cancel',
        changePassword: 'Change Password',
        city: 'City',
        confirmPassword: 'Confirm New Password',
        country: 'Country',
        delete: 'Delete',
        deleteAddress: 'Delete Address',
        deleteAddressConfirm: 'Are you sure you want to delete the address?',
        details: 'Details',
        edit: 'Edit',
        editAddress: 'Edit Address',
        editDetails: 'Edit Details',
        email: 'Email',
        fieldRequired: 'This field is required',
        name: 'Full Name',
        newAddress: 'New Address',
        newPassword: 'New Password',
        oldPassword: 'Old Password',
        passwordMismatch: 'Passwords don\'t match',
        phoneNumber: 'Phone Number',
        postalCode: 'Postal Code',
        save: 'Save',
        state: 'State',
        title: 'My Account',
        update: 'Update',
        vatin: 'VAT Identification Number',
        vatLabel: 'VAT'

    },
    pt: {
        address: 'Morada',
        addresses: 'Moradas',
        cancel: 'Cancelar',
        changePassword: 'Alterar Password',
        city: 'Cidade',
        confirmPassword: 'Confirmar Nova Password',
        country: 'País',
        delete: 'Apagar',
        deleteAddress: 'Apagar Endereço',
        deleteAddressConfirm: 'Tem a certeza que deseja apagar o endereço?',
        details: 'Detalhes',
        edit: 'Editar',
        editAddress: 'Editar Endereço',
        editDetails: 'Editar Detalhes',
        email: 'E-Mail',
        fieldRequired: 'Este campo é obrigatório',
        name: 'Nome Completo',
        newAddress: 'Nova Morada',
        newPassword: 'Nova Password',
        oldPassword: 'Password Antiga',
        passwordMismatch: 'As palavras-passe não são iguais',
        phoneNumber: 'Número de Telefone',
        postalCode: 'Código Postal',
        save: 'Guardar',
        state: 'Estado',
        title: 'A Minha Conta',
        update: 'Actualizar',
        vatin: 'Número de Identificação Fiscal',
        vatLabel: 'NIF'
    }
};
