import keyMirror from 'react/lib/keyMirror';

export default keyMirror({
    APPLICATION_CHANGE_ROUTE: null,
    APPLICATION_ROUTE_ERROR: null,
    APPLICATION_DRAWER_TRIGGER: null,
    APPLICATION_LOCALE_SET: null,
    APPLICATION_MOBILE_BREAKPOINT_SET: null,
    APPLICATION_PAGE_WIDTH_CHANGED: null,
    APPLICATION_POST_NOTIFICATION: null,
    APPLICATION_POP_NOTIFICATION: null,
    APPLICATION_PAGE_LOADING_TRIGGER: null
});
