export default {
    en: {
        back: 'Back',
        categories: 'Categories',
        collections: 'Collections',
        currency: 'Currency',
        delete: 'Delete',
        description: 'Description',
        enabled: 'Enabled',
        fieldRequired: 'This field is required',
        homepage: 'Homepage',
        listPrice: 'List Price',
        mainCategory: 'Main Category',
        mainCollection: 'Main Collection',
        name: 'Name',
        pricing: 'Pricing',
        retailPrice: 'Retail Price',
        save: 'Save',
        sections: 'Featured in Sections',
        sku: 'SKU',
        stock: 'Stock',
        title: 'Edit Product',
        type: 'Type',
        vat: '% VAT (Included)'
    },
    pt: {
        back: 'Voltar',
        categories: 'Categorias',
        collections: 'Colecções',
        currency: 'Moeda',
        delete: 'Remover',
        description: 'Descrição',
        enabled: 'Activada',
        fieldRequired: 'Este campo é obrigatório',
        homepage: 'Página Principal',
        listPrice: 'Preço Recomendado',
        mainCategory: 'Categoria Principal',
        mainCollection: 'Colecção Principal',
        name: 'Nome',
        pricing: 'Preço',
        retailPrice: 'Preço Final',
        save: 'Guardar',
        sections: 'Destaque nas Secções',
        sku: 'SKU',
        stock: 'Stock',
        title: 'Editar Produto',
        type: 'Tipo',
        vat: '% IVA (Incluído)'
    }
};
